### ISSUE TITLE
'WebSocketType' object has no attribute 'upper'

### ISSUE THREAD

**Issue by erasmush** [jonathanelscpt/valr-python#12]
Hi Jonathan,

I'm getting the following error when running the example websocket code:

File "c:/Users/Desktop/Python/.py", line 29, in <module>
    hooks={TradeEvent.MARKET_SUMMARY_UPDATE : pretty_hook})
  File "C:\Users\AppData\Local\Programs\Python\Python37\lib\site-packages\valr_python\ws_client.py", line 883, in __init__
    self._ws_type = WebSocketType[ws_type.upper()]
AttributeError: 'WebSocketType' object has no attribute 'upper'

I have tried on both windows and linux with python 3.6 and 3.7.

I have entered my api key and secret but no other changes to code. Am I missing something obvious?

Any direction will be greatly appreciated.

**Comment by jonathanelscpt** [comment]
let me review and get back to you.

**Comment by erasmush** [comment]
Thank you, please let me know if I can provide any further info.

**Comment by jonathanelscpt** [comment]
I added enum support and there's a regression which I've missed because I haven't added unit tests yet (have an issue open for that.)

Please try the following:

```
import asyncio
import os
from typing import Dict
from pprint import pprint
from valr_python import WebSocketClient
from valr_python.enum import TradeEvent
from valr_python.enum import WebSocketType


key = os.environ['VALR_KEY']
secret = os.environ['VALR_SECRET']


def pretty_hook(data: Dict):
    pprint(data)

if __name__ == '__main__':
    c = WebSocketClient(api_key=key, api_secret=secret, currency_pairs=['BTCZAR'],
                    ws_type=WebSocketType.TRADE.name,
                    trade_subscriptions=[TradeEvent.MARKET_SUMMARY_UPDATE.name],
                    hooks={TradeEvent.MARKET_SUMMARY_UPDATE.name : pretty_hook})
    loop = asyncio.get_event_loop()
    loop.run_until_complete(c.run())
```

Alternatively, drop just use strings instead of the enums.

Apologies will fix this asap.

**Comment by jonathanelscpt** [comment]
Please consider the WS API to still be beta.  if you face more issues, please raise them and I'll address them asap.

**Comment by erasmush** [comment]
Thanks for the feedback and help, it is much appreciated.
