### ISSUE TITLE
Websocket Support for Solana

### ISSUE THREAD

**Issue by erasmush** [jonathanelscpt/valr-python#15]
Hi Jonathan,

Are you planning on adding support for Solana? 

Really appreciate the library!

**Comment by jonathanelscpt** [comment]
Hi,

Shpuld be simple as its just enum support.  Will try and fit it in during
this week sometime!  Need to check if more updates are required on the
website side.  REST is now up to date.

**Comment by jonathanelscpt** [comment]
Had a look at this.  Besides adding helper enum support, I think that nothing else actually needs to change in the websocket code.  VALR DOES already support SOLZAR, even though their docs are wrong.  I'll contact their dev team and request an update to the docs....  So even without this update, you can use the lib for following all Solana events...

**Comment by erasmush** [comment]
Hi Jonathan,

Thats great news, thank you very much!

**Comment by jonathanelscpt** [comment]
necessary minor changes are live and available in:
https://pypi.org/project/valr-python/0.2.7/

**Comment by erasmush** [comment]
Fantastic, thanks Jonathan
