### ISSUE TITLE
Request has an invalid signature

### ISSUE THREAD

**Issue by OnTheRicky** [jonathanelscpt/valr-python#7]
I'm getting the following error when trying to run **post_simple_quote()**

> APIError: (-11252, 'Request has an invalid signature')

Reproduce:
```
from valr_python import Client
c = Client(api_key=xxx,api_secret=xxx)
response = c.post_simple_quote(currency_pair="BTCZAR", pay_in_currency="ZAR", pay_amount=5, side="BUY")
```

MacOS 10.15.4
Python 3.7
valr_python==0.1.7

**Comment by jonathanelscpt** [comment]
think i see your issue already.

```
from valr_python import Client
c = Client(api_key=xxx,api_secret=xxx)
response = c.post_simple_quote(currency_pair="BTCZAR", pay_in_currency="ZAR", pay_amount=5, side="BTC")
```

[](https://docs.valr.com/?version=latest#8c1df98d-5878-44f0-9090-2211f793fd6f)

```
{
    "payInCurrency": "BTC",
    "payAmount": "0.001",
    "side": "SELL"
}
```


`'side'` is an enum, as in either BUY or SELL.  I'm trying to keep the SDK as a thin client, so am not doing validation on this and am bubbling errors from valr.

can you try again with this?

**Comment by OnTheRicky** [comment]
Hi Jonathan, apologies, I typed `"BTC"` in the issue, but it is actually `"BUY"` on my side. 
I've double checked all fields again in case, but still getting the error.

**Comment by jonathanelscpt** [comment]
let me try and reproduce... will get back to you.

**Comment by jonathanelscpt** [comment]
yeah, bug is valid and i'm getting a false positive on my unit test for this.  will have to investigate.

**Comment by OnTheRicky** [comment]
Hi Jonathan, 

Thanks for the update, I think I might have picked up the issue. 
https://github.com/jonathanelscpt/valr-python/blob/v0.1.7/src/valr_python/base_client.py#L136
and 
https://github.com/jonathanelscpt/valr-python/blob/v0.1.7/src/valr_python/base_client.py#L138
use different timestamps, but they should be the same timestamp according to the VALR API docs.

**Comment by jonathanelscpt** [comment]
i'm using the same timestamp, but am casting to a str afterwards for the header.  may well be the issue.  let me review.  thanks for the heads up.

**Comment by OnTheRicky** [comment]
I'm sorry I don't know how I crossed those up, but I see they are in-fact using the same timestamp.

I tried the sign_request method with the test data provided on Valr API docs and got a different result. 

> In [57]: sign_request("1558017528946","POST","/v1/orders/market",
>     ...: '{"customerOrderId":"ORDER-000001","pair":"BTCZAR","side
>     ...: ":"BUY","quoteAmount":"80000"}',"4961b74efac86b25cce8fbe
>     ...: 4c9811c4c7a787b7a5996660afcc2e287ad864363")             
> Out[57]: '989aaa6068b722875c461cfb268f1d7b122139a492e67cd8ee2aa39
> ecbdb1c0190274a7d4ebe95bdca3239be24947b53d180824d5ef13e9a9dd462bb
> 06ee3f0d'
> 
> In [58]: _sign_request("1558017528946","POST","/v1/orders/market"
>     ...: ,'{"customerOrderId":"ORDER-000001","pair":"BTCZAR","sid
>     ...: e":"BUY","quoteAmount":"80000"}',"4961b74efac86b25cce8fb
>     ...: e4c9811c4c7a787b7a5996660afcc2e287ad864363")            
> Out[58]: '399d6292aaeb66ef46a49aa65e8bdca6dcb16e742608f627bdbd10a
> 22ad94693690786dd33009f904f3b6e524cebce2d75cd60e2cfd01f585baed96d
> 6145494e'

the only real difference I can see between the two is how you format your payload vs their example: 

`payload = "{}{}{}{}".format(timestamp,verb.upper(),path,body)`
vs 
`payload = f"{timestamp}{method.upper()}{path}{body}"`

**Comment by jonathanelscpt** [comment]
Both are returning the same for me?

```
>>> sign_request("1558017528946","POST","/v1/orders/market",'{"customerOrderId":"ORDER-000001","pair":"BTCZAR","side":"BUY","quoteAmount":"80000"}',"4961b74efac86b25cce8fbe4c9811c4c7a787b7a5996660afcc2e287ad864363")
'989aaa6068b722875c461cfb268f1d7b122139a492e67cd8ee2aa39ecbdb1c0190274a7d4ebe95bdca3239be24947b53d180824d5ef13e9a9dd462bb06ee3f0d'
```

```
>>> _sign_request("1558017528946","POST","/v1/orders/market",'{"customerOrderId":"ORDER-000001","pair":"BTCZAR","side":"BUY","quoteAmount":"80000"}',"4961b74efac86b25cce8fbe4c9811c4c7a787b7a5996660afcc2e287ad864363")
'989aaa6068b722875c461cfb268f1d7b122139a492e67cd8ee2aa39ecbdb1c0190274a7d4ebe95bdca3239be24947b53d180824d5ef13e9a9dd462bb06ee3f0d'
>>>
```

**Comment by jonathanelscpt** [comment]
I believe that i've found the problem.  working on a solution.

**Comment by jonathanelscpt** [comment]
Found the issue.  presenting a string representation of a body dict didn't translate into the exact same string from json serialization, resulting in a signature mismatch.  This is why get_balance worked, but post_simple_quote failed.

Will commit a fix and publish a new release after further testing...
